# --- CATALOGO DE APLICACIONES (BLOATWARE VS SEGURAS) ---
# Define las listas de apps para la herramienta de limpieza.

$script:AppLists = @{
    
    # 1. LISTA BLANCA (VERDE): Apps del sistema que NO se deben borrar
    #    Borrar estas puede romper la tienda, calculas o visualizacion de imagenes.
    Safe = @(
        "Microsoft.WindowsStore"
        "Microsoft.WindowsCalculator"
        "Microsoft.Windows.Photos"
        "Microsoft.Windows.Camera"
        "Microsoft.SecHealthUI"
        "Microsoft.UI.Xaml"
        "Microsoft.VCLibs"
        "Microsoft.NET.Native"
        "Microsoft.WebpImageExtension"
        "Microsoft.HEIFImageExtension"
        "Microsoft.VP9VideoExtensions"
        "Microsoft.ScreenSketch"
        "Microsoft.WindowsTerminal"
        "Microsoft.Paint"
        "Microsoft.WindowsNotepad"
    )


    # 2. LISTA NEGRA (NARANJA): Bloatware recomendado para borrar
    #    Publicidad, pruebas, apps de terceros preinstaladas, etc.
    Bloat = @(
        "Microsoft.Microsoft3DViewer"
        "Microsoft.3DBuilder"
        "Microsoft.BingSearch"
        "Microsoft.BingFinance"
        "Microsoft.BingFoodAndDrink"
        "Microsoft.BingHealthAndFitness"
        "Microsoft.BingNews"
        "Microsoft.BingSports"
        "Microsoft.BingTranslator"
        "Microsoft.BingTravel"
        "Microsoft.BingWeather"
        "Microsoft.WindowsAlarms"
        "Microsoft.549981C3F5F10"
        "Microsoft.Copilot"
        "Microsoft.Windows.DevHome"
        "Microsoft.Windows.AIHub"
        "Microsoft.PCManager"
        "Microsoft.GetHelp"
        "Microsoft.Getstarted"
        "Microsoft.Messaging"
        "Microsoft.MicrosoftJournal"
        "Microsoft.MicrosoftOfficeHub"
        "Microsoft.MicrosoftPowerBIForWindows"
        "Microsoft.MicrosoftSolitaireCollection"
        "Microsoft.MicrosoftStickyNotes"
        "Microsoft.MixedReality.Portal"
        "Microsoft.NetworkSpeedTest"
        "Microsoft.News"
        "Microsoft.Office.OneNote"
        "Microsoft.Office.Sway"
        "Microsoft.OneConnect"
        "Microsoft.People"
        "Microsoft.PowerAutomateDesktop"
        "Microsoft.Print3D"
        "Microsoft.SkypeApp"
        "Microsoft.Todos"
        "Microsoft.Wallet"
        "Microsoft.WindowsCamera"
        "Microsoft.WindowsFeedbackHub"
        "Microsoft.WindowsMaps"
        "Microsoft.WindowsSoundRecorder"
        "MicrosoftCorporationII.MicrosoftFamily"
        "MicrosoftCorporationII.QuickAssist"
        "microsoft.windowscommunicationsapps"
        "MicrosoftTeams"
        "MSTeams"
        "Microsoft.Xbox.TCUI"
        "Microsoft.XboxApp"
        "Microsoft.XboxGameOverlay"
        "Microsoft.XboxGamingOverlay"
        "Microsoft.XboxIdentityProvider"
        "Microsoft.XboxSpeechToTextOverlay"
        "Microsoft.GamingApp"
        "Microsoft.ZuneMusic"
        "Microsoft.ZuneVideo"
        "Microsoft.YourPhone"
        "Microsoft.Edge.GameAssist"
        "Microsoft.MSPaint"
        "Clipchamp.Clipchamp"
        "9P1J8S7CCWWT"
        "9NBLGGH4QGHW"
        "Amazon.com.Amazon"
        "AmazonVideo.PrimeVideo"
        "Disney"
        "Disney.37853FC22B2CE"
        "Duolingo-LearnLanguagesforFree"
        "Facebook"
        "FarmVille2CountryEscape"
        "Instagram"
        "Netflix"
        "PandoraMediaInc.Pandora"
        "Spotify"
        "Twitter"
        "TwitterUniversal"
        "YouTube"
        "Plex"
        "TikTok"
        "TuneInRadio"
        "king.com.BubbleWitch3Saga"
        "king.com.CandyCrushSaga"
        "king.com.CandyCrushSodaSaga"
    )
}
